vrk-kpa/api-catalog

ansible/roles/ckan/files/patches/fix-popped-wrong-app-context.patch
ansible/roles/ckan/vars/main.yml

- Upgrade CKAN to 2.8.3
- patch for ckan/ckan#4431

LIKA-26: Upgrade CKAN to 2.8.3, add patch for ckan/ckan#4431

---

ansible/roles/ckan/tasks/main.yml
ansible/roles/ckan/templates/ckan.ini.j2
ansible/roles/ckan/vars/main.yml
ansible/vars/secrets-defaults.yml
ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/commands.py
ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/harvesterstatusplugin.py
ckanext/ckanext-apicatalog_routes/setup.py

Adds ckan_harvester_status_email_recipients to secrets.
PULL NEW SECRETS!

LIKA-21: Add harvest status report plugin and run it as cron job

---

ansible/roles/ckan/files/patches/fix_password_reset.patch
ansible/roles/ckan/vars/main.yml

Simple fix for password reset, already fixed in ckan master.

LIKA-58: Fix password reset

---

ansible/roles/ckan-translations/files/ckan.pot
ansible/roles/ckan-translations/files/en_GB.po
ansible/roles/ckan-translations/files/fi.po
ansible/roles/ckan-translations/files/sv.po
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/plugin.py
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/admin/useradd.html
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/views/useradd.py

- Added a view for adding users to admin tools

LIKA-72 user add view

---

ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/home/snippets/twitter.html

- Change twitter timeline URL and label

LIKA-74: Change twitter feed from vrk_uutiset to suomifi

---

ansible/roles/ckan/tasks/database.yml
ansible/roles/ckan/templates/ckan.ini.j2
ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/auth.py
ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/commands.py
ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/db.py
ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/plugin.py
ckanext/ckanext-apicatalog_routes/setup.py
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/plugin.py
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/schema.py
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/validators.py

User_create auth function still need to be modified to allow specific users to create other users.
Does not add to organizations yet as the process needs to be spefied.

LIKA-127: Add create user to organization api

---

ansible/roles/ckan-translations/files/ckan.pot
ansible/roles/ckan-translations/files/en_GB.po
ansible/roles/ckan-translations/files/fi.po
ansible/roles/ckan-translations/files/sv.po
ansible/roles/ckan/templates/ckan.ini.j2
ansible/vars/environment-specific/prod.yml
ansible/vars/environment-specific/qa.yml
ansible/vars/environment-specific/test.yml
ansible/vars/environment-specific/vagrant.yml
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/commands/migrate.py
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/schemas/organization.json
ckanext/ckanext-apicatalog_scheming/setup.py

- Scheming model for organizations
- Added new organization fields
- New content migration system based on a version graph

LIKA-108: Organization scheming model

---

ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/schemas/organization.json
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action/create.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/model.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/notification_email.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views/__init__.py

- Added permission application notification email template
- Added sending such emails to specified email address

LIKA-105: permission application notification

---

ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/apicatalog_header.html
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/contact/snippets/form.html
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/footer.html
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/home/snippets/apicatalog_profile.html
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/organization/snippets/organization_item.html
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/package/snippets/resources_list.html
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/snippets/facet_list.html
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/snippets/package_item.html
ckanext/ckanext-apicatalog_ui/less/dataset.less
ckanext/ckanext-apicatalog_ui/less/masthead.less
ckanext/ckanext-apicatalog_ui/less/search.less
ckanext/ckanext-apicatalog_ui/less/variables.less

Accessibility fixes according to the accessibility review.

LIKA-95: Accessibility fixes

---

ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/templates/scheming/package/read.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action/get.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/plugin.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/manage.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/view.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/package/edit_base.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views/__init__.py

- Hide "request access" link for own APIs
- Added management view for permission applications of a subsystem

LIKA-126: Subsystem permission request list view

---

ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/plugin.py
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/schemas/dataset.json
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/templates/scheming/package/read.html
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/validators.py
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/fanstatic/javascript/mutexfield.js
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/fanstatic/resource.config
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/helpers.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/ckanext-apply_permissions_for_service.pot
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/en_GB/LC_MESSAGES/ckanext-apply_permissions_for_service.po
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/fi/LC_MESSAGES/ckanext-apply_permissions_for_service.po
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/sv/LC_MESSAGES/ckanext-apply_permissions_for_service.po
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action/__init__.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action/create.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action/get.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action/update.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/auth/get.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/plugin.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/settings.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/snippets/request_access_button.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/package/edit_base.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views/__init__.py

**Note: review and merge LIKA-126 PR first**
- Added dataset field for premission request settings object
- Added permission request settings view
- Modified functionality of permission request button and notification based on setting values

LIKA-125: Permission request settings

---

ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/templates/scheming/package/resource_read.html
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/page.html

- Added override blocks for primary and secondary content column sizes
- Added overrides for resource page to allow for wider resource views

LIKA-124: Added column layout overrides for resource page

---

ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/package/snippets/resources_list.html
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/snippets/tag_list.html
ckanext/ckanext-apicatalog_ui/less/dataset.less

- Make all subheadings `<h3>`
- Change interface/attachment lists to new style

LIKA-75: Harmonize dataset view subheading fonts

---

ansible/roles/ckan-translations/files/ckan.pot
ansible/roles/ckan-translations/files/en_GB.po
ansible/roles/ckan-translations/files/fi.po
ansible/roles/ckan-translations/files/sv.po
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/plugin.py
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/home/layout1.html
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/home/snippets/announcement_content.html
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/home/snippets/announcement_title.html
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/home/snippets/announcements.html

- Determine front page announcements from harvester user's activity
- Added templates for generating title and content for announcement items

LIKA-79: Added implementation for frontpage announcements

---

ansible/roles/ckan/files/patches/correctly_unflatten_extras.patch
ansible/roles/ckan/vars/main.yml

- Added patch for https://github.com/ckan/ckan/pull/5546

Add CKAN patch that fixes extras flattening

---

ansible/roles/ckan/tasks/main.yml
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/schemas/organization.json

- Separate action + paster command for updating organization data
- Cron job for daily updates

LIKA-151: xroad organization update job

---

ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/admindashboard.py
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/plugin.py
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/utils.py

- Front page stats did not fetch all results from `package_search` resulting in a truncated number of new APIs

LIKA-229: Fix front page package stats by actually fetching all packages

---

ansible/roles/ckan-translations/files/ckan.pot
ansible/roles/ckan-translations/files/en_GB/LC_MESSAGES/en_GB.po
ansible/roles/ckan-translations/files/fi/LC_MESSAGES/fi.po
ansible/roles/ckan-translations/files/sv/LC_MESSAGES/sv.po
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/admindashboard.py
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/fanstatic/javascript/modules/tablesorter.js
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/fanstatic/javascript/plugins/jquery.tablesorter.js
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/fanstatic/resource.config
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/admin/dashboard.html
ckanext/ckanext-apicatalog_ui/less/tables.less

- Moved admindashboard help text to the top of the page to give the content more horizontal space
- Added jquery-tablesorter, created a ckan data module for adding it to tables and simple styling for column sorting
- Implemented fetching subsystemless organizations and how long they've been subsystemless
- Added subsystemless organizations view to admin dashboard

LIKA-211: subsystemless orgs view

---

ansible/roles/ckan/tasks/main.yml
ansible/roles/ckan/templates/ckan.ini.j2
ansible/vars/environment-specific/vagrant.yml

Certificates on actual environments still need to be solved.

LIKA-212: Add X-Road statistics

---

ansible/roles/ckan/tasks/main.yml
ansible/roles/ckan/templates/ckan.ini.j2

- Added `fetch_service_list` paster command
- Added cronjob definition to ansible

LIKA-226: xroad service list cronjob

---

ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/fanstatic/cookieconsent/ckan-cookieconsent.css
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/fanstatic/cookieconsent/ckan-cookieconsent.js

- Move revoke button to bottom position
- Add slight style to the button

LIKA-286: Move cookieconsent revoke button to the bottom of the page

---

ansible/roles/ckan-extension/tasks/main.yml
ansible/roles/postgres/tasks/main.yml
ansible/roles/postgres/templates/pg_hba.conf.j2
ansible/vars/environment-specific/vagrant.yml
ansible/vars/secrets-defaults.yml

Default database password is changed as it is common convention to use pass as testing password

Configure local testing in vagrant

---

ansible/roles/ckan/tasks/main.yml

- Update submodule
- Add cronjob for sending batch run emails

LIKA-300: Add scheduled batch run email sending

---

ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/health.py
ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/plugin.py
ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/views.py

- Port apicatalog_routes.health to Flask
- Added `/xroad_catalog_heartbeat` route for checking if xroad_catalog is up

LIKA-314: xroad-catalog heartbeat

---

ansible/roles/ckan/templates/ckan.ini.j2
ansible/roles/piwik/tasks/packages_apt.yml
ansible/roles/piwik/tasks/piwik_ubuntu.yml
ansible/roles/piwik/templates/nginx_piwik.j2
ansible/roles/piwik/vars/main.yml
ansible/vars/environment-specific/prod.yml
ansible/vars/environment-specific/qa.yml
ansible/vars/environment-specific/test.yml
ansible/vars/environment-specific/vagrant.yml
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/plugin.py
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/page.html

Adds cloud matomo as a secondary location where analytics are posted and fixes piwik installation on bionic.

LIKA-302: Add matomo

---

ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/emails/invite_user.txt
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/emails/invite_user_subject.txt

- Added override templates for user invite email subject/body

LIKA-186: Customize user invite email template

---

ansible/roles/ckan/templates/ckan.ini.j2
ansible/roles/ckan/vars/main.yml
ansible/vars/secrets-defaults.yml
ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/commands.py

Stuck harvester report from open data. Vars are added to secrets.

LIKA-312: Add stuck harvester report

---

ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/page.html

Possibility to require consent only to cookies, currently requires consent to all tracking.

LIKA-307: Use matomo consent api

---

ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/home/snippets/announcements.html

The function is not named as index.

LIKA-358: Fix announcements link

---

ansible/roles/nginx/templates/nginx_site_config.j2
ansible/roles/nginx/vars/main.yml
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/package/read.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/settings.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py

- Set Nginx max body size
- Make request form data multipart
- Fix file upload

LIKA-326: fix service access application pdf attachments

---

ansible/roles/ckan-translations/vars/main.yml
ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/plugin.py
ckanext/ckanext-apicatalog_scheming/.tx/config
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/i18n/ckanext-apicatalog_scheming.pot
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/i18n/en_GB/LC_MESSAGES/ckanext-apicatalog_scheming.po
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/i18n/fi/LC_MESSAGES/ckanext-apicatalog_scheming.po
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/i18n/sv/LC_MESSAGES/ckanext-apicatalog_scheming.po
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/presets.json
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/schemas/dataset.json
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/translations.py
ckanext/ckanext-apicatalog_scheming/setup.cfg

- Added translation support to ckanext-apicatalog_scheming
- Schema changes
- Added a new scheming preset for organization autocomplete
- Change resource filtering to work with user organizations

LIKA-322: Rework resource user restrict feature to work on organization level

---

ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/plugin.py
ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/schemas/dataset.json

Subsystems must be private for it to be hidden from others.

LIKA-328: Add organization visibility controls to subsystems

---

ansible/roles/ckan/templates/ckan.ini.j2
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/plugin.py
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/page.html

Analytics auth tokens are updated in secrets.

LIKA-303: Fetch frontpage statistics from matomo

---

ansible/roles/ckan-translations/files/en_GB/LC_MESSAGES/en_GB.po
ansible/roles/ckan-translations/files/fi/LC_MESSAGES/fi.po
ansible/roles/ckan-translations/files/sv/LC_MESSAGES/sv.po
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/error_document_template.html
ckanext/ckanext-apicatalog_ui/less/ckan.less

Fix padding on the error page (page not found) template and update translations from transifex

LIKA-387 fix padding and pull translations from transifex

---

ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/error_document_template.html

LIKA-387: fix padding on the page not found template

LIKA-387: fix padding

---

ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/i18n/ckanext-apicatalog_ui.pot
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/i18n/en_GB/LC_MESSAGES/ckanext-apicatalog_ui.po
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/i18n/fi/LC_MESSAGES/ckanext-apicatalog_ui.po
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/i18n/sv/LC_MESSAGES/ckanext-apicatalog_ui.po
ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/package/read.html

LIKA-434 fix localizations of services and attachments on subsystem page

LIKA-434 fix localizations of services and attachments on subsystem page

---

.github/pull_request_template.md

Fixes rendering of checkboxes in PR template.

Fix PR template rendering of checkboxes

---

ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/templates/scheming/display_snippets/fluent_tag_list.html

LIKA-465: Updated route from package to dataset

---

ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/ckanext-apply_permissions_for_service.pot
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/en_GB/LC_MESSAGES/ckanext-apply_permissions_for_service.po
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/fi/LC_MESSAGES/ckanext-apply_permissions_for_service.po
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/sv/LC_MESSAGES/ckanext-apply_permissions_for_service.po
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/migration/apply_permissions_for_service/versions/e2fdr852000b_add_intermediate_organization.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/model.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/new.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/settings.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py

LIKA-413: intermediate organization to permission application form.
Added a dropdown for intermediary organization to the "settings template" for permission management
Added a read-only field for Y-number for intermediary organization, filled according to the organization dropdown
Added a checkbox for the dropdown field

LIKA-413: intermediate organization to permission application form

---

ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/cli.py

Fixed some issues with changed functionality when python was upgraded
- Updated iterations in harvester email reports

Lika 461 fix email reports about harvesters

---

ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/plugin.py

Convert keywords to lowercase.
Converted keywords to lowercase.

LIKA-296: keywords are case sensitive

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/home/snippets/apicatalog_profile_items.html

Prod is broken due to not merging previous fix
Cherry picked https://github.com/vrk-kpa/api-catalog/commit/123911cb4e4ed569e3617921e51a1cb6f4e7004e

Check if extensions is enabled before generating url

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/fi/LC_MESSAGES/ckanext-apicatalog.po

The subsystem edit form seemed to already be following the Suomi.fi design (couldn't find any differences to the linked design) but I did fix one missing fi translation (sv still missing)
Added one finnish translation

LIKA-410: Update translations

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py

- Improve logging
- Refactor xroad harvester, add better typing information and error handling
- Remove unnecessary logging from apicatalog plugin
- Standardize xroad maybe-list handling
- Add typing information
- Detect errors in service description downloads
- Cover unexpected edge cases in data without crashing

LIKA-453: Improve logging and edge case handling

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/en_GB/LC_MESSAGES/ckanext-apicatalog.po
ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/fi/LC_MESSAGES/ckanext-apicatalog.po
ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/sv/LC_MESSAGES/ckanext-apicatalog.po

Update ckanext-apicatalog translations
Updated translation files

Updated ckanext-apicatalog translations

---

ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/index.html

Make permission application list subsystem/service/organization references links
- Changed various text references into links to the referenced objects

LIKA-510: Add links to permission application list

---

ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/ckanext-apply_permissions_for_service.pot
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/en_GB/LC_MESSAGES/ckanext-apply_permissions_for_service.po
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/fi/LC_MESSAGES/ckanext-apply_permissions_for_service.po
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/sv/LC_MESSAGES/ckanext-apply_permissions_for_service.po
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/settings.html

Added  GDPR note to service permission application settings page
- Added text
- Added translations

LIKA-518: Added GDPR note to service permission application settings

---

ansible/vars/environment-specific/qa.yml

QA has been updated to focal for some time now.

Use focal variables in qa

---

ansible/vars/environment-specific/vagrant.yml

Xroad dev env was rebuilt, variables for it are updated.

Update variables for dev xroad

---

ansible/vars/environment-specific/test.yml

Test environment upgraded to focal /postgres 12
- Update vars for test

Upgrade test server to ubuntu focal/postgres 12

---

ansible/vars/environment-specific/prod.yml

Update production ubuntu+postgres versions
- Update config

Update production ubuntu+postgres versions

---

ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/ckanext-apply_permissions_for_service.pot
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/new.html

Error messages were only shown at the top of the page, add them next to the inputs as well
- Added error message parameters to inputs
- Updated translation file
- Changed service code list validation to reject an empty list

LIKA-525: Improve error messages in service permission application form

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/schemas/dataset.json

Remove attachment visibility from resource view additional info table
* Remove attachment visibility from resource view additional info table

LIKA-498: Remove attachment visibility from resource view 

---

ansible/roles/ckan-translations/files/en_GB/LC_MESSAGES/ckan.po
ansible/roles/ckan-translations/files/sv/LC_MESSAGES/ckan.po
ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/ckanext-apicatalog.pot
ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/en_GB/LC_MESSAGES/ckanext-apicatalog.po
ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/fi/LC_MESSAGES/ckanext-apicatalog.po
ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/sv/LC_MESSAGES/ckanext-apicatalog.po
ckanext/ckanext-apicatalog/ckanext/apicatalog/validators.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/en_GB/LC_MESSAGES/ckanext-apply_permissions_for_service.po
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/fi/LC_MESSAGES/ckanext-apply_permissions_for_service.po
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/sv/LC_MESSAGES/ckanext-apply_permissions_for_service.po

Fix error message for invalid business code verification number
- Change the error message
- Update translations

LIKA-527: Fix error message for invalid business code verification number

---

.github/workflows/main.yml
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/tests/test_plugin.py

The form accepted an empty list as value.
- Check that the value is a list which has at least one non-empty value
- Added tests

LIKA-556: Improve service permission application ip address list validation

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
ckanext/ckanext-apicatalog/ckanext/apicatalog/schemas/organization.json
ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/organization/about.html
ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/scheming/display_snippets/fluent_email_list.html
ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/scheming/form_snippets/extra_label.html
ckanext/ckanext-apicatalog/ckanext/apicatalog/validators.py

Fixes issues in organization edit form: Nested list in every email translation field. Some information not shown up on about-page.
- [x ] Contains schema changes.

LIKA-558: Fix organization edit and about pages.

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/emails/reset_password.txt
ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/emails/reset_password_subject.txt

Added trilingual password reset email template with email subject only in finnish by design
* Added trilingual password reset email template

LIKA-273: Update password reset email templates

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/emails/invite_user.txt
ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/emails/invite_user_subject.txt

Updated the trilingual new user email template. Email subject only in finnish by design
* Updated the trilingual new user email template.

LIKA-505: Update new user email templates

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/organization/about.html

Added is_intermediary display to organization about page
- Added a conditional list item for showing intermediary status
- Reformatted the additional information section condition

LIKA-547: Added is_intermediary display to organization about page

---

ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/new.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/snippets/application_table.html
ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py

LIKA-572: Fix org vs intermediate org

---

.github/workflows/main.yml
ansible/roles/ckan/tasks/database.yml

Updates changes from [vrk-kpa/ckanext-xroad_integration/](https://github.com/vrk-kpa/ckanext-xroad_integration/pull/51) and adds alembic migration to ansible

Update xroad integration and init error database in ansible

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
ckanext/ckanext-apicatalog/ckanext/apicatalog/schemas/dataset.json
ckanext/ckanext-apicatalog/ckanext/apicatalog/schemas/organization.json
ckanext/ckanext-apicatalog/ckanext/apicatalog/utils.py
ckanext/ckanext-apicatalog/ckanext/apicatalog/validators.py

Instead of removing members/subsystems/services which have been marked as removed on X-Road, mark them with xroad_removed property
- Added `xroad_removed` property to members, subsystems and services in data model
- Updated `ckanext-xroad_integration` to populate the field
- Modified `after_show` and `after_search` to filter entities removed from X-Road *for non-admins*
- Also refactored determining resources the user is allowed to see in these
- Added a debug validator for debugging data model issues

LIKA-337: X-Road soft remove

---

ansible/vars/environment-specific/vagrant.yml

Xroad dev environment is up again, the configuration required some changes.

Update xroad configuration

---

ansible/vars/environment-specific/prod.yml
ansible/vars/environment-specific/qa.yml
ansible/vars/environment-specific/test.yml

AV-2151: Update environment developer lists

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/footer.html
ckanext/ckanext-apicatalog/gulpfile.js
ckanext/ckanext-apicatalog/less/forms.less
ckanext/ckanext-apicatalog/package-lock.json
ckanext/ckanext-apicatalog/package.json

Font Awesome / footer update
- Update Font Awesome to version 6
- Update footer social links
- Remove leftover cookieconsent references

LIKA-586: Font Awesome 6, update footer

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/schemas/dataset.json

Support for xroad-catalog's getRest interface
- Update ckanext-xroad_catalog
- Add `rest_endpoints` field to service data model

LIKA-393: Implement harvesting and storing REST endpoint data

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/home/layout1.html

Show three news items on front page
- Changed news item count in template

LIKA-587: Show three news items on front page

---

ckanext/ckanext-apicatalog/less/icons.less

Added support for producing endpoint previews for REST services
- Implement generating OpenAPI descriptions from REST endpoint data
- Add `rest` as a supported resource type in ckanext-openapiviewer
- Add resource icon rules for REST services

LIKA-393: Generate REST service previews

---

ansible/vars/environment-specific/prod.yml
ansible/vars/environment-specific/qa.yml
ansible/vars/environment-specific/test.yml

Updates sentry dsn to the new sentry organization and updates sentry extension.

LIKA-617: Update sentry dsn and extension

---

ansible/roles/ckan/templates/ckan-uwsgi.ini.j2

Test was in a harakiri loop, these changes fixed it

Tune uwsgi limits in ckan task and enable threads to fix harakiri loop

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/home/layout1.html

Front page activity list seems to create a high database load.
- Commented out the announcements section of the front page for testing purposes. Will delete entirely or revert later.

Disable front page announcements to test performance impact

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/home/layout1.html

Finalize removing announcement block from front page
- Remove commented out code

Actually remove the announcement block

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py

If user hasn't been logged in, `auth_user_obj` contains anonymous user which doens't have sysadmin attribute.

Fix dataset show for anonymous users

---

ansible/roles/ckan/files/patches/remove_free_fontawesome.patch
ansible/roles/ckan/vars/main.yml
ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/snippets/resource_view.html

Upgrades openapi viewer and replaces url helper with url_for. Removes core ckan fontawesome as it conflicts with pro version we supply ourselves.

Fix issues in ckan upgrade

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/auth.py

`user/register` is producing an error as `group_id` might not exist.

Fix user/register producing an error

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/snippets/service_alerts.html
ckanext/ckanext-apicatalog/scss/forms.scss

Fix service alert close button

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/apicatalog_header.html
ckanext/ckanext-apicatalog/scss/nav.scss

Fix nav submenu

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/organization/index.html
ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/organization/read.html
ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/search.html

Fix missing class from pagination

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/ckanext-apicatalog.pot
ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/footer.html

The new link doesn't have lang code, so it need to go through translations.

LIKA-642: Update privacy policy link and extract messages

---

ansible/roles/ckan/tasks/main.yml

Removes xroad organization cronjob.

LIKA-649: Remove xroad organization update from use

---

.github/workflows/main.yml

Removing push removed tests on master all together 😞

Run workflow on push to master

---

ckanext/ckanext-apicatalog/ckanext/apicatalog/tests/test_plugin.py

Added some unit tests for auth functions

Added tests for auth functions
