vrk-kpa/api-catalog

- ansible/roles/ckan/tasks/main.yml
- ansible/roles/ckan/tasks/override_requirements.yml
- ansible/roles/ckan/templates/override_requirements.txt.j2
- Added `override_requirements.txt` to install pip packages over CKAN's requirements
- Install psycopg2 2.8.2 to fix libssl compatibility issues
> Update psycopg2 to a version compatible with libssl-1.1.x

- ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/plugin.py
- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/plugin.py
- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/organization/index.html
- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/snippets/search_form.html
- Have empty organization list sorting value correspond to "alphabetically ascending, grouped descendingly by existence of data sets"
- Implement sorting in a separate helper that fetches all organizations and does sorting/paging manually
- Add the new default sorting schema as sorting by "Relevance"
> LIKA-6: Custom default sorting solution for organizations via a helper

- ckanext/ckanext-apicatalog_ui/less/forms.less
- ckanext/ckanext-apicatalog_ui/less/layout.less
- Make the triangle `pointer-events: none` to allow clicking through it
- Remove text padding to fix element focus area
> LIKA-36: Allow clicking select box arrows and fix focus area

- ansible/roles/ckan/files/patches/disable_leftover_with_capacity.patch
- ansible/roles/ckan/vars/main.yml
- ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/plugin.py
- In some execution paths `with_capacity` remains in context when it should not. This causes some dictization functions to fail since their parameter format is determined by it
- `access_level_restriction` defaulted to never-visible, since empty value was not taken into account. This caused crashes when creating a new resource with default values, as the newly created resource was not visible to the code that created it
> LIKA-61: Fix with_capacity leftover and access_restriction_level related errors

- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/ckanext_pages/pages_list.html
- The block the button normally is in is not visible in current theme. Override template to move it into content.
> LIKA-62: Move missing ckanext-pages page button into content

- ansible/roles/ckan/files/patches/add_samesite_flag.patch
- ansible/roles/ckan/templates/ckan.ini.j2
- ansible/roles/ckan/templates/override_requirements.txt.j2
- ansible/roles/ckan/vars/main.yml
Beaker and repoze.who are updated for samesite flag support. repoze.who is locked specific commit as it has not released a new version to pypi yet.
> LIKA-67: Add samesite flag to authentication token

- .gitmodules
- ansible/roles/ckan/vars/main.yml
- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/pages.py
- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/ckanext_pages/base_form.html
- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/ckanext_pages/page.html
- ckanext/ckanext-apicatalog_ui/setup.py
- Change from ckanext-pages fork to upstream
- Added schema extension to ckanext-pages into ckanext-apicatalog_ui to support multilingual content and titles
- Added template overrides to display multilingual content
> LIKA-68: Switch from modified ckanext-pages to extending

- ansible/deploy-all.yml
- ansible/roles/mailhog/.yamllint
- ansible/roles/mailhog/README.md
- ansible/roles/mailhog/defaults/main.yml
- ansible/roles/mailhog/handlers/main.yml
- ansible/roles/mailhog/meta/main.yml
- ansible/roles/mailhog/molecule/default/INSTALL.rst
- ansible/roles/mailhog/molecule/default/molecule.yml
- ansible/roles/mailhog/molecule/default/playbook.yml
- ansible/roles/mailhog/molecule/default/prepare.yml
- ansible/roles/mailhog/molecule/default/tests/test_default.py
- ansible/roles/mailhog/tasks/main.yml
- ansible/roles/mailhog/templates/mailhog.service.j2
- ansible/roles/mailhog/vars/main.yml
- ansible/vars/environment-specific/vagrant.yml
The role is copied from [opendata](https://github.com/vrk-kpa/opendata), only other changes are in deploy-all.yml and vagrant variables to send mail to mailhog itself.
> Add mailhog to vagrant

- ansible/roles/ckan/files/patches/remove_is_sysadmin_or_user_itself_check.patch
- ansible/roles/ckan/templates/ckan.ini.j2
- ansible/roles/ckan/vars/main.yml
- ansible/vars/environment-specific/qa.yml
- ansible/vars/environment-specific/vagrant.yml
- ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/auth.py
- ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/plugin.py
- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/user/edit_user_form.html
Includes modification to core controllers where edit form is assumed to be used by sysadmin or the user itself.
New auth functions check that the modified user are not sysadmins.
> LIKA-128: Add auth function for modifying users

- ansible/roles/ckan/files/patches/retain_allow_anonymous_access_in-chained_auth.patch
- ansible/roles/ckan/vars/main.yml
- ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/auth.py
User show and user update require auth_allow_anonymous_access and chained auth function do not retain them. There is a related ckan issue ckan/ckan#4597
> LIKA-130: Fix internal server error in password reset

- ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/auth.py
- ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/plugin.py
- Added CKAN configuration variable `ckanext.apicatalog_routes.allowed_user_editors` that contains a list of users allowed to view and edit organization members for all organizations
> LIKA-133: Added configurable member editor privileges

- ansible/roles/ckan-translations/files/ckan.pot
- ansible/roles/ckan-translations/files/en_GB/LC_MESSAGES/en_GB.po
- ansible/roles/ckan-translations/files/fi/LC_MESSAGES/fi.po
- ansible/roles/ckan-translations/files/sv/LC_MESSAGES/sv.po
- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/organization/index.html
- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/organization/snippets/search_form.html
- ckanext/ckanext-apicatalog_ui/less/layout.less
- Move "Show organizations without APIs" seach filter above sorting
- Fix a bug when changing sorting while filtering by existence of APIs
> LIKA-174: Reorganize organization search inputs

- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/commands/migrate.py
- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/plugin.py
- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/presets.json
- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/schemas/organization.json
- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/templates/scheming/display_snippets/fluent_email_list.html
- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/templates/scheming/display_snippets/fluent_list.html
- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/templates/scheming/form_snippets/fluent_list.html
- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/validators.py
- Implemented fluent_list scheming preset
- Modified organization data model: changed email_address into fluent_list with email customizations
- Created a migration from single emails to multilingual lists of emails
- Implemented update_xroad_organizations multilingual email list support
> LIKA-157: multilingual organization email address lists

- Vagrantfile
- ansible/ansible.cfg
- ansible/roles/ckan-extension/tasks/main.yml
- ansible/roles/ckan-ui/defaults/main.yml
- ansible/roles/ckan/tasks/main.yml
- ansible/roles/ckan/templates/ckan.ini.j2
- ansible/roles/ckan/vars/main.yml
* Refactors Vagrantfile to use ansible_local instead of custom shell script
* Mounts host directories to default vagrant instead of src
* Adds X-Road rest service certificate check to ansible but does not fail play if they are missing, instead it notifies about them like so
> Refactor Vagrantfile and add certificate configuration

- ansible/vars/environment-specific/qa.yml
Uses openapi described apis instead of manually configured ones.
> Update rest path in qa and store number of other services to db

- ansible/roles/ckan/tasks/database.yml
- ckanext/ckanext-validate_links/ckanext/validate_links/commands/validate_links.py
- ckanext/ckanext-validate_links/ckanext/validate_links/model/__init__.py
- ckanext/ckanext-validate_links/ckanext/validate_links/templates/admin/broken_links.html
* Adds clear command to cli, which clears all broken links from db.
* Calls clear before crawl as old results might not be relevant anymore.
* Add user agent to requests.
* Adds Reason for failure to the database and view.
* Add migrate command to add reason column to database.
> LIKA-223: Clear old broken links from db

- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/package/snippets/tags.html
- CKAN styles tags using `.tag` on tag content, but suomifi theme uses `.tag-list > li`. Removed `.tag` to only style the list items, not the contents.
> LIKA-287: remove conflicting tag styling

- ansible/roles/ckan/files/patches/fix_uploading_images.patch
- ansible/roles/ckan/vars/main.yml
- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/schemas/organization.json
Replaces resource uploader preset with organization image uploader in organization schema.
Adds patch from ckan core to fix image uploads itself.
> Fix image uploads in organizations and site_logo

- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/apicatalog_header.html
- ckanext/ckanext-apicatalog_ui/less/masthead.less
- If main nav "more" menu has only one item, show it without the menu
- Show correct language title for menu items
- Allow main nav overflow instead of wrapping
> LIKA-336: One item main nav extra menu

- ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/commands.py
- ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/db.py
- ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/plugin.py
- ckanext/ckanext-apicatalog_routes/setup.py
- Implemented `UserForOrganization`methods for querying pending and previously failed instances
- New admin-only action `create_organization_users` to match account applications into organizations and sending user invites
- Added a paster command for running the added action with a human-readable summary
> LIKA-200: Added command for processing user_for_organization applications

- ansible/roles/ckan/tasks/main.yml
- ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/plugin.py
- Create organization users through api as organization admins
- Added a cronjob for processing users for organizations
> LIKA-200: organization-user-add cronjob & role change

- ansible/roles/ckan/tasks/database.yml
* Updates ckanext-pages
* Moves pages database initialization to cli (https://github.com/ckan/ckanext-pages/pull/112)
* Adds cli initdb to ansible.
> LIKA-141: Move pages db initialization to cli

- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/apicatalog_header.html
- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/ckanext_pages/base_form.html
* Pages resource path changed in python3 migration.
* Template rendering fails on UnicodeDecodeError when there is "{}".format(someunicodevariable)
> Fix errors in logs

- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/organization/index.html
`with_datasets` parameter was changed in to `provider_orgs` in https://github.com/vrk-kpa/api-catalog/pull/74
> LIKA-361: Fix provider_orgs parameter in pagination

- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/package/search.html
LIKA-356: Hide info text about trying different search terms from sidebar and add it into main content area
> LIKA-356: Move try another search terms info to main content

- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/plugin.py
- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/utils.py
- Added `organization_generator` that works like `package_generator` to fetch organizations in multiple batches while defaulting to page size set by `ckan.group_and_organization_list_max`
- Use `organization_generator` in organization listings and statistics
> LIKA-382: Fix organization list truncation

- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/templates/scheming/package/read.html
- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/macros/form.html
- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/snippets/multiselect.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/auth.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/new.html
- Fix the "request access" button visibility to depend on authorization to create service permission applications
- Modify `service_permission_application_create` auth function to only allow users that could create datasets to some organization (editors and admins)
> LIKA-331: Only editors and admins can apply service access

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/auth.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/settings.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/view.html
Limits permission for viewing permission applications.
Replaces sending requests with api to email.
Fixes breadcrumb build failure.
> LIKA-369: Limit viewing permission applications to org members

- ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/plugin.py
Admin lost access to subsystem as the labeling function caused an error on list with an empty string on it.
> LIKA-416: Fix 404 error when allowed organizations list is empty

- ansible/vars/environment-specific/qa.yml
- ansible/vars/environment-specific/test.yml
- ansible/vars/environment-specific/vagrant.yml
Test environment for news has been down for awhile https://palveluhallinta.test.suomi.fi/api/articles/importantTopical, this PR replaces news source to production environment in all environments.
> LIKA-422: Use prod environment for news in all environments

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/auth.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/model.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/new.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/notification_email.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/view.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py
* Modifies the database schema to store both applicant organization and target organization to handle permissions for each.
* Adds lookup for applicant and target organization to auth check.
* Adds the whole organizations to model dictize to handle what is shown on the UI.
> LIKA-369: Limit viewing permission applications to receiving and applying org members

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/new.html
Searching for organization fails when search with title, it only accepts id or name.
Selecting the requesting organization needs to be solved though.
> LIKA-369: Use name instead of title in permission application organizations

- ansible/roles/ckan/tasks/main.yml
- ansible/roles/ckan/templates/robots.txt.j2
- ansible/roles/ckan/templates/robots_disallowed.txt
- ansible/roles/ckan/vars/main.yml
Adds a template for modifying robots.txt and block some bots that appear to crawl production.
Following bots are bloked:
* Petalbot
* Ahrefsbot
* Semrushbot
[ ] Contains schema changes.
[ ] Schema changes require migration of existing data.
[ ] Contains migration script for existing data.
[ ] Changes should be covered by tests.
[ ] Changes are covered by tests.
[ ] Yes 
[x] No
> LIKA-455: Add template to robots.txt and block some bots

- .github/workflows/main.yml
- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/plugin.py
- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/presets.json
- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/schemas/dataset.json
- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/validators.py
Prevents adding non-existent organizations in UI by not accepting them in selection and ignores them in the backend code if they are added through api.
Adds createtags false in the component to prevent selecting non-existent. Adds a new validator to ignore them in backend.
> LIKA-440: Prevent adding non-existent organizations to allowed organizations

- ckanext/ckanext-apicatalog_routes/ckanext/apicatalog_routes/plugin.py
Sysadmin check was never passed as .get('sysadmin') was always None, parsing allowed organizations was failing as user_orgs sometimes expected to be list of strings and sometimes list of dicts.
* Fix sysadmin check in after_show.
* Added sysadmin check to after_search.
* Fixed parsing user_orgs in various checks.
> Fix issues with sysadmin check and parsing allowed organizations

- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/home/snippets/apicatalog_profile_items.html
Makes permission request applications available from ui-link (instead of remembering correct url and writing it directly on browser)
- Added link in profile menu
> LIKA-377: Add link for list applications view in profile menu

- ckanext/ckanext-apicatalog_scheming/ckanext/apicatalog_scheming/schemas/dataset.json
Adds file upload field back to the dataset resource schema.
- Dataset schema, added url field back for resource
> LIKA-473: Add file upload field back to dataset resources schema

- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/group/new.html
CKAN template for new group form gives an error about undefined group_dict so this defines that as an empty dict if it's not already defined
- Override group/new template with definition of group_dict if it's undefined
> LIKA-231: Fix error about undefined group_dict in new group form

- Vagrantfile
- ansible/roles/ckan/tasks/database.yml
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/cli.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/migration/apply_permissions_for_service/versions/09e3ebeb1e37_create_apply_permissions_table.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/migration/apply_permissions_for_service/versions/13981b4847ac_add_intermediate_organization_columns.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/migration/apply_permissions_for_service/versions/e7cd24026024_add_application_file_column.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/model.py
Fixes various issues when building a new environment.
Installs pip for python 3.6 to allow install of ansible.
Moves creation of apply_permission table to alembic and re-creates migrations. This is the current recommendation of ckan and running migrations to database which already had the columns failed. This requires dropping of existing tables in environments but this should not matter as the feature is not really released to end users yet.
> Fix provision on vagrant

- ansible/roles/ckan/tasks/main.yml
- ansible/roles/ckan/templates/beaker_session_cleanup.sh.j2
- ansible/roles/ckan/templates/ckan.ini.j2
Change configs to use database based sessions and add cleanup script for beaker sessions. Also configure cron job for cleanup script
- Ckan configurations session type
- New script to clean deprecated sessions from database
- Added new cron job in ansible configuration
> LIKA-456: Store sessions into the database

- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/macros/form.html
- ckanext/ckanext-apicatalog_ui/less/components.less
- ckanext/ckanext-apicatalog_ui/less/components/apply-permissions-for-service.less
- ckanext/ckanext-apicatalog_ui/less/components/banner.less
- ckanext/ckanext-apicatalog_ui/less/components/button.less
- ckanext/ckanext-apicatalog_ui/less/forms.less
- ckanext/ckanext-apicatalog_ui/less/module.less
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/ckanext-apply_permissions_for_service.pot
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/en_GB/LC_MESSAGES/ckanext-apply_permissions_for_service.po
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/fi/LC_MESSAGES/ckanext-apply_permissions_for_service.po
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/sv/LC_MESSAGES/ckanext-apply_permissions_for_service.po
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/new.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/preview.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/settings.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/snippets/additional_application_info.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py
Implement a new view for permission application form preview.
- Added new route on apply_permission-plugin
- Added new template for preview
> LIKA-433: Implement a new view for previewing an permission application form

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/model.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/notification_email.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/view.html
Allow intermediate organization to be empty if not empty add relevant information to permission view and notification email
Allow intermediate organization to be empty if not empty add relevant information to permission view and notification email.
Allow intermediate organization to be empty if not empty add relevant information to permission view and notification email
> LIKA-413: allow intermediate organization to be empty if not empty add relevant information to permission view and notification email

- ansible/roles/ckan/files/patches/email_attachment.patch
- ansible/roles/ckan/vars/main.yml
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/helpers.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
Add support for additional info as an attachment in email
Add support for additional info file as an attachment in email confirmation about permission application
- Add 6535 patch about email attachments. 
- Include additional file in email that is sent when permission application is created
> LIKA-415: Support additional permission application file in email

- ckanext/ckanext-apicatalog_ui/ckanext/apicatalog_ui/templates/package/snippets/resources.html
- ckanext/ckanext-apicatalog_ui/less/dataset.less
Prevent line-breaks on attachments name so that overflow attribute works as expected
Add description of PR here.
- Added css to prevent line breaks on attachments name in resource view
- Removed python based truncate from attachments-list as it's done by css now
> LIKA-357: Fix attachments-list in resource view

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/ckanext-apply_permissions_for_service.pot
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/en_GB/LC_MESSAGES/ckanext-apply_permissions_for_service.po
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/fi/LC_MESSAGES/ckanext-apply_permissions_for_service.po
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/sv/LC_MESSAGES/ckanext-apply_permissions_for_service.po
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/index.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py
Refacto view for user permission applications.
Refactored view for user permission applications.
> LIKA-368: refacto view for user permission applications

- ckanext/ckanext-apicatalog/ckanext/apicatalog/fanstatic/javascript/collapsible.js
Javascript was failing on "Unexpected string", which was caused by "use strict" during bundling. 
Removed "use strict" from one of the js files.
Updated ckanext-sentry.
> Fix javascript error on form page

- ansible/roles/ckan/tasks/main.yml
Add cron job for fetching xroad distinct services daily.
Add cron job for fetching xroad distinct services daily.
> LIKA-488: add cron job for fetching xroad distinct services daily

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/edit.html
Generating urls to apply permissions failed when apply permission is not enabled.
Added add check if apply permission is enabled
> Fix dataset edit when apply permission is not enabled

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/edit_base.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/page.html
- ckanext/ckanext-apicatalog/less/dataset.less
- ckanext/ckanext-apicatalog/less/layout.less
- ckanext/ckanext-apicatalog/less/module.less
Dataset form layout modification were too extensive which broke other pages, this narrows it somewhat.
Adds a new css class to dataset form and styles it.
Fixed dataset list:
Fixed organization list:
Dataset form is still working design:
> LIKA-492: fix layout problems

- Vagrantfile
- ansible/roles/ckan/tasks/main.yml
- ansible/roles/os-base/templates/sources.list.j2
- ansible/roles/os-base/vars/main.yml
- ansible/roles/postgres/tasks/main.yml
- ansible/roles/postgres/templates/postgresql.conf.j2
- ansible/vars/common.yml
- ansible/vars/environment-specific/vagrant.yml
Upgrade vagrant environment to Ubuntu 20.04 (focal)
- Change base image in Vagrantfile
- Parametrize postgres version in ansible
- Make `ubuntu_codename` and postgres version environment-specific variables
- Add workaround for `typing` python package causing errors when installing CKAN
> LIKA-493: Upgrade Vagrant environment to Ubuntu 20.04 (focal)

- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/sv/LC_MESSAGES/ckanext-apicatalog.po
Swedish translation for a format string had a type, which caused rendering errors
Fixed the format string
> LIKA-421: Fix swedish dashboard by fixing translate string format

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/scheming/form_snippets/fluent_tags_with_autocomplete.html
Remove unnecessary asset directive that causes errors.
https://sentry.io/organizations/gofore-b3/issues/3276655324
Removed reference to api-catalog-select2 asset since it is already included in `main_js` bundle
> LIKA-421: Remove unnecessary asset directive

- ansible/roles/os-base/tasks/developer-users.yml
- ansible/roles/os-base/tasks/main.yml
- ansible/vars/secrets-defaults.yml
- ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
Create developer accounts during deploy
- Added new secret value: developers
- Added ansible tasks for creating/removing developer accounts
> LIKA-342: Add option to create developer accounts for environments

- ansible/roles/os-base/tasks/developer-users.yml
- ansible/vars/common.yml
- ansible/vars/environment-specific/prod.yml
- ansible/vars/environment-specific/qa.yml
- ansible/vars/environment-specific/test.yml
- ansible/vars/secrets-defaults.yml
Remove developers from secrets and add them to environment configurations
- Remove developers from secrets
- Add developers to environment configurations
- Modify ansible tasks accordingly
> LIKA-342: Move developers from secrets to environment-specific variables

- ansible/roles/os-base/tasks/developer-users.yml
- ansible/roles/os-base/templates/sudoers.d.developers.j2
Create a new user group `developers` for developer user accounts to handle sudo configuration
- Create `developers` user group
- Add developer users to this group instead of `sudo`
- Create specific sudo configuration for the group
> LIKA-342: Create a new user group for developers

- ckanext/ckanext-apicatalog/ckanext/apicatalog/schemas/dataset.json
This removes duplicated information, internal information (doesn't interest the user) and empty rows from subsystem and resource additional info tables
* Hide (null display_snippets) for description and keywords that are already separately listed above
* Hide (null display snippets) for privateness(?) and allowed organizations
* Hide empty rows (rows without values). Template change at [vrk-kpa/ckanext-scheming](https://github.com/vrk-kpa/ckanext-scheming) level so it affects both LIKA and AV
Technically yes but as it only hides some rows the impact is minimal
> LIKA-498: Clean up unnecessary fields from subsystem/resource additional info table

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/scheming/package/read.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/scheming/package/resource_read.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/snippets/request_access_button.html
Removes the old permission application links from both subsystem page and resource page
Removed the old permission application links from both subsystem page and resource page
Technically yes, although I'd say it very much depends on your definition of impact... 
There was a link
Now there's not
There used to be a link
Now there's not
> LIKA-484: Remove old permission application links

- ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
Fix some errors during harvesting
- Fix crash in ckanext-apicatalog `after_search` if no user object in global context
- Remove request context from harvester jobs to fix after_search authorization during harvesting
> LIKA-453: Fix harvest errors

- ckanext/ckanext-apicatalog/ckanext/apicatalog/helpers.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/ckanext-apicatalog.pot
- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/en_GB/LC_MESSAGES/ckanext-apicatalog.po
- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/fi/LC_MESSAGES/ckanext-apicatalog.po
- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/sv/LC_MESSAGES/ckanext-apicatalog.po
- ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/schemas/dataset.json
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/resource_edit.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/snippets/resource_edit_form.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/scheming/package/snippets/resource_form.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/translations.py
Resource edit page now refers to a "service" or "attachment" depending on the property `harvested_from_xroad`
- Added a helper `with_field_string_replacements` to create modified versions of scheming field lists
- Utilized the helper to change "attachment" substrings to "service" in specific labels
- Updated translations
- Fixed a typo bug in translations where a change in a variable name caused issues rendering organization pages
Rendering pages with several languages should be a part of testing, but not in scope for this PR.
> LIKA-467: Choose resource edit form labels based on resource type

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/admin/statistics.html
Fixed stats page to use correct prop names and formatted dates
* Switched to use correct prop names (underscore_case vs camelCase)
* Formatted dates
* Actually tested the changes (inserted data into DB so I could verify I didn't do a dummy again)
> LIKA-495: Fix stats to use correct prop names and format dates

- ansible/roles/ckan/files/patches/fix_updating_resource_filesize.patch
- ansible/roles/ckan/vars/main.yml
Added a CKAN core patch to fix resource file size not updating on reupload.
- Added a patch file
- Enabled patch
> LIKA-453: CKAN core patch to fix resource file size updating

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/edit_base.html
apply_permissions_for_service is not enabled in production, check if it is before use
-
Add check for plugin
> Hotfix: check if apply_permissions_for_service plugin is loaded

- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/ckanext-apicatalog.pot
- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/en_GB/LC_MESSAGES/ckanext-apicatalog.po
- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/fi/LC_MESSAGES/ckanext-apicatalog.po
- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/sv/LC_MESSAGES/ckanext-apicatalog.po
- ckanext/ckanext-apicatalog/ckanext/apicatalog/translations.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
Validate email and business code values when creating service access requests.
- Added calls to `email_validator` and `business_id_validator` validators when creating applications
- Updated translations because CKAN validation error `"Email {email} is not a valid format"` was not translated
> LIKA-514: Validate service access application values

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/settings.html
Changed permission application settings view upload label from "Image URL" to "File"
- Changed input label
> LIKA-507: Change service permission application settings upload label

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/home/snippets/apicatalog_profile_items.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/user/dashboard.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/base.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/dashboard.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/index.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/sent.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/snippets/application_table.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py
Move service permission application list to dashboard
- Added `apply_permissions.dashboard` view
- Replaced "My groups" with "Service access applications" in user dashboard tabs
- Removed profile menu item for service access applications
- Modified breadcrumbs to point to the dashboard instead of the list view
> LIKA-511: Move service permission application list to dashboard

- ckanext/ckanext-apicatalog/less/multiselect.less
Custom checkboxes used in service permission application overflowed in Chrome by a pixel, causing scrollbars
- Change checkbox style to avoid the issue
> LIKA-516: Fix vertical scrollbars in custom checkbox when using chrome

- Vagrantfile
- ansible/roles/ckan-extension/tasks/main.yml
We don't need ton install pip separately anymore and old linking sources was done using hard coded paths.
> Fix building vagrant environment

- ckanext/ckanext-apicatalog/less/layout.less
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/new.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/snippets/organization_select.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py
Implement proper organization select for service permission application form
- Make prelude have dynamic size, because long headers wrap under content
- Added snippet for organization select
- Rewrite service permission application organization/intermediate organization parts
- Add intermediate organization business code validation
- Harmonize code style
> LIKA-442: better organization selection inputs for service applications

- ansible/roles/ckan/files/patches/csrf.patch
- requirements.in
- requirements.txt
Upgrade CKAN to 2.9.7
- Update dependencies
- Fix CSRF patch
> LIKA-536 ckan 2.9.7

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/new.html
Add warning for unsaved changes in service permission application when navigating away
- Add `form-change-listener` data module on service permission application form
> LIKA-528: Add warning for unsaved changes in service application

- ansible/roles/ckan/files/patches/fix_resource_delete_auth.patch
- ansible/roles/ckan/vars/main.yml
- ckanext/ckanext-apicatalog/ckanext/apicatalog/auth.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/tests/test_plugin.py
Users should be able to delete attachments (resources not harvested from X-Road), but not services.
- Added override auth function for resource_delete
- Added patch to fix ckan.views.resource.DeleteView's auth functions
- Added tests
> LIKA-523: attachment delete auth

- ckanext/ckanext-apicatalog/ckanext/apicatalog/fanstatic/javascript/multiselect.js
Multiselect elements are missing a space
Use string concatenation instead of template strings. Rjsmin [had a bug that removes spaces from template strings](https://github.com/miracle2k/webassets/issues/511) and CKAN only has the updated version in master through `webassets==2.0`
> LIKA-534: Work around rjsmin bug to fix multiselect label

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/apicatalog_header.html
Remove Data Exchange Layer info link from header
- Removed link
> LIKA-526: Remove Data Exchange Layer info link from header

- ckanext/ckanext-apply_permissions_for_service/.github/workflows/test.yml
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/model.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/new.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/tests/fixtures.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/tests/test_plugin.py
- ckanext/ckanext-apply_permissions_for_service/test.ini
Only show subsystems that belong to the selected organization in permission application subsystem select
- Added a function to hide subsystem options that don't belong to the selected (intermediate) organization
> LIKA-515: Hide subsystem options in permission application based on selected organization

- ckanext/ckanext-apicatalog/ckanext/apicatalog/helpers.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
Overriding lang() broke javascript translations, this fixes the original issue by overriding scheming_language_text instead
Removes overridden lang().
Overrides scheming_language_text()
> LIKA-537: Fix failing lang parameter

- ckanext/ckanext-apicatalog/less/components.less
- ckanext/ckanext-apicatalog/less/components/warning-container.less
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/settings.html
Styled GDPR warning according to design
- Added a LESS component for a warning box like in the design
- The colors are defined ad-hoc because they don't match suomi.fi colors
- Utilize style in service permission application settings
> LIKA-518: Style GDPR warning according to design

- ckanext/ckanext-apicatalog/less/forms.less
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/snippets/organization_select.html
Made basic select2 component suomi.fi-styled
- Added styling for basic select2 controls
- Made the organization select box explicitly full-width (required by select2 to inherit the width correctly)
> LIKA-515: Style organization select component

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/home/layout1.html
Remove "show all" links from hero, make the text itself a link
- Reorganize hero links
> LIKA-533: Reorganize front page hero links

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
If `package_show` is called without `id`, it will raise an validation error before auth check is done, this will in some cases return an error that auth function is not called.
If subsystem code is missing, do not call `package_show`
> Fix server error in service applications

- ckanext/ckanext-apicatalog/ckanext/apicatalog/schemas/dataset.json
Validator order with ignore_not_sysadmin being the last validator caused the harvested_from_xroad to be dropped from all resources of the dataset when dataset changes were saved by a non-sysadmin user
* Changed validator order with ignore_not_sysadmin being the first validator like in it already was for the other fields
> LIKA-546: Fix harvested_from_xroad disappearing from resources

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/settings.html
Changed access request settings form to use the whole page width
* Increased the width access request settings view uses
Before:
After:
> LIKA-545: Give access request settings page more width

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/apicatalog_header.html
- ckanext/ckanext-apicatalog/less/dropdown.less
- ckanext/ckanext-apicatalog/less/masthead.less
Previously if there was only one CMS page it was shown in the main nav otherwise they were all collapsed into a dropdown. But with the removal of (tietoa palveluväylästä hard coded nav item) there's enough space to show the 2 first CMS pages and collapse rest under the "more options" dropdown menu.
* Show first 2 CMS pages on main nav and collapse the rest into a dropdown menu
Before:
After:
> LIKA-544: Show first 2 cms pages on main nav

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/read.html
Keep selected language when navigating to service permission application
- Use CKAN's `h.url_for` instead of the generic `url_for` to fix the link
> LIKA-535: Fix service permission application link language

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py
Subsystem id was not given to auth check which produces an error. Also fixes viewing previews which weren't allowed if settings weren't saved.
> Fix application previews

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/user/dashboard.html
- ckanext/ckanext-apicatalog/less/layout.less
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/auth.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/model.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/dashboard.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/snippets/application_table.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py
In user's dashboard the view to access requests (apply_permissions_for_service) it used to list ALL access requests (and I mean ALL). Now it was split to show the access requests sent by the organizations the user has read permissions to and received by the organizations the user had read permissions to
* Changed auth function to take into account package_update permissions if fetching specific package's access requests
* Changed API to return dict with user's(/user's org's) sent and received access requests lists 
* Implemented sub navigation to the access requests page in dashboard
* Changed the page to list only one request per subsystem even if it includes requests for multiple services
Before:
After:
> LIKA-539: Separate sent and received access requests

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/edit_base.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/resources.html
(Branched from blocking issue LIKA-427/PR https://github.com/vrk-kpa/api-catalog/pull/339)
Remove attachments link from subsystem edit side navigation (the add attachment button was added to subsystem read in LIKA-427). Since attachments link took to the same place as the newly added "reorder resources" button it's page title was also changed and the side nav removed.
* Removed link to 'attachments' from subsystem edit
* Changed the "reorder resources" view (/dataset/resources/) page title to reflect the "new usage" and removed the side nav
Before:
After:
> LIKA-428: Remove attachments from subsystem edit nav

- ckanext/ckanext-apicatalog/ckanext/apicatalog/cli.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/tests/fixtures.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/tests/test_plugin.py
- ckanext/ckanext-apicatalog/test.ini
Previously `create_organization_users` discarded applications that referred to email addresses of existing users. Modified the process to interpret such applications as requests to add existing users to organizations.
- Modified `create_organization_users`  to handle applications for existing users
- Modified apicatalog CLI to report the added users separately
- Added tests for both cases
> LIKA-543: Modify organization user add API to allow adding existing users to organizations

- .github/workflows/main.yml
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/read_base.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/resource_edit.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/page.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/package/read_base.html
At some point some read pages with no side nav got too wide and it was starting to get difficult to read full page wide content. This changes pages without side nav to only use 8/12 cols instead of all 12. Also tweaks side navs to not appear with only one link as it was felt such navs are pointless.
I'm not particularly happy with simply moving the package_update check around the secondary content as it's not particularly intuitive but all the other links were already using that check so it sort of made sense to simply expand it.
* Only show side nav if there's more than one link
* If no nav reduce primary content width
* Updated python-version from 3.6 to 3.8 as 3.6 reached end of life 
Before:
After:
> LIKA-550: Reduce content width on pages without side nav

- ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/snippets/resource_item.html
On subsystem page the resources lists (services and attachments) always showed finnish description regaradless of current_lang. Seems like description was used instead of description_translated so translations were never even used. When description_translated was used there was still issue with i18n.get_lang returning 'en_GB' and not matching that against 'en' translation
* Switched resource_item template to use description_translated instead of description
* Switched to use get_lang_prefix() instead of i18n.get_lang()
> LIKA-538: Resource description always in finnish

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/footer.html
- ckanext/ckanext-apicatalog/less/footer.less
Moved link to source code in the top part of the footer down to the bottom part next to social media icons
* Moved link to source code in the top part of the footer down to the bottom part next to social media icons
Before:
After:
> LIKA-551: Move link to source code next to some icons

- ckanext/ckanext-apicatalog/ckanext/apicatalog/schemas/organization.json
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/organization/about.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/scheming/form_snippets/multiple_checkbox.html
- ckanext/ckanext-apicatalog/less/forms.less
Add option to save information regarding organization's data processing outside EU. Simple checkbox on org level.
* Add a single checkbox to org form / boolean to org schema and simple text on org about page if it's set.
New checkbox to edit form and simple text on org about page if it's set.
> LIKA-552: Add data_processing_outside_eu boolean option to org schema

- ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/home/layout1.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/organization/index.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/organization/snippets/search_form.html
Switch organizations page to list only provider orgs by default (old provider_orgs filter) and move all orgs behind request param.
* Change default organizations list to be filtered to only provider orgs
> LIKA-554: List only provider orgs by default

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/read.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/settings.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py
You can now add optional guide text (in all 3 languages) at subsystem level in the access request / apply_permission settings. 
This will be show between the access request button and the original info text.
* Add guide_text_translated markdown field to apply_permission settings
* Add it to subsystem read between the delivery methods' original info text and the button
> LIKA-553: Add optional guide text to apply permission settings

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/read.html
The access request button on a subsystem where access requests were enabled was shown to everyone (also without login) regardless of whether they had the permission to do so (it did however lead to 403 page). This change hides it from people who are not supposed to see it
* Hide the access request stuff from those without permissions to actually create the requests
> LIKA-557: Hide access request button from those without permissions

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/i18n/ckanext-apply_permissions_for_service.pot
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/new.html
Adds a new group description field for intermediary org in access request / permission application form.
* Added a new group description field for intermediary org in access request / permission application form.
> LIKA-548: Add group description for intermediary org

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/scheming/organization/group_form.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/new.html
Some pages / forms were accidentally made too narrow when narrowing content on some other pages in LIKA-550 by narrowing the container around them. This fixes all found views with too narrow content (that was previously narrowed in those views specifically and thus ended up being double narrowed) which incidentally were the ones specified in the issue. 
* Removed content narrowing scheming/organization/group_form (outer container is already narrowed)
* Removed content narrowing apply_permissions_for_service/new (outer container is already narrowed)
Before:
After:
> LIKA-560: Fix too narrow pages

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/read.html
Subsystem page template depended on apply_permissions_for_service. 
- Added if around the permission application stuff
> hotfix: subsystem page should work without apply_permissions_for_service extension

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/snippets/resources.html
This change separates the resource pages side nav according to resource type i.e. services and attachments
* Split resource page side nav to services and attachments
Before:
After:
> LIKA-435: Separate resource page side nav to services and attachments

- .gitmodules
Clones fail with git url if host keys are not added.
> Use https url for sitesearch extension

- ckanext/ckanext-validate_links/ckanext/validate_links/cli.py
- ckanext/ckanext-validate_links/ckanext/validate_links/model/__init__.py
- ckanext/ckanext-validate_links/ckanext/validate_links/templates/admin/broken_links.html
- ckanext/ckanext-validate_links/ckanext/validate_links/views.py
- Try to guess the organization whose content has invalid links during crawling
- Show the organizations in broken link report
- Added `organization` field to `LinkValidationReferrer` and updated `links migrate` cli command to migrate database
- Store guessed organization in the field
- Show organization links in broken links report
- Updated ckanext-contact to clean up flask developer toolbar template tab
> LIKA-270: Guess relevant organizations for broken link scan results

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/macros/form.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py
On apply permission settings add validators to raise an error when additional file or permission application file is missing
- Additional file required -validation
- Permission application file missing -validation
- Disabled wrongly shown errors from drag-n-drop uploader
> LIKA-483: Add missing validation for additional file and permission application pdf

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/organization/bulk_process.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/snippets/search_form.html
- ckanext/ckanext-apicatalog/less/components.less
- ckanext/ckanext-apicatalog/less/components/bulk-process.less
- ckanext/ckanext-apicatalog/less/search.less
Added stylings for bulk-edit view in organizations datasets
- Styles
- Structure of that pages layout
> LIKA-424: New stylings for bulk-edit page for organization datasets

- ckanext/ckanext-apicatalog/less/forms.less
- ckanext/ckanext-apicatalog/less/layout.less
- ckanext/ckanext-apicatalog/less/variables/palette.less
Update info box styles.
- Styles for alert/danger/success/info toasts/alerts
> LIKA-371: Match info box styles with suomi.fi like design

- ckanext/ckanext-apicatalog/ckanext/apicatalog/utils.py
- tools/generate_organizations.py
Change organization list to use solr instead of sql to make it faster
- Combine list of organizations with faster solr queries
- Add organization generate script in tools
> LIKA-438: Use sitesearch extension in organization list

- ckanext/ckanext-apicatalog/ckanext/apicatalog/validators.py
Old organization have old_business_ids stored as empty strings and updates fail.
If old_business_ids is a empty string, output it as list which can be stored again.
> If stored old_business_ids is a empty string, output it as list

- ckanext/ckanext-apicatalog/ckanext/apicatalog/fanstatic/cookieconsent/ckan-cookieconsent.js
The cookieconsent library's info url was never changed so it pointed to the lib's default. This changes it to use the simple cms page tietoa-evasteista instead 
* Added info url to the cookieconsent.initialise
> LIKA-563: Change cookieconsent info url

- ckanext/ckanext-apicatalog/less/module.less
The sidenav layout got broken if navigation elements text wrapped to multiple lines. This change lets the height flex correctly in case the text doesn't fit on one line
* Changed sidenav li set height to min-height to let it flex upwards
- [x Yes 
Before:
After:
> LIKA-566: Let sidenav element height flex for multiline text

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/notification_email.html
The link to the dataset in the access request notification email template was a relative url which resolved incorrectly. This change turns the link into a fully qualified url that takes the ckan.site_url and ckan.root_path settings into account.
* Use absolute url instead of relative
> LIKA-565: Make the link in access request received email a fully qualified URL

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/settings.html
This change adds a description text to the access request settings view's email fields. Between the label and the field as per instructions.
* Added description to apply permission settings email fields
> LIKA-568: Add description to apply permission settings email fields

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/settings.html
The 'Request additional info with an attachment' file upload input got incorrect width likely due to the js shenanigans with input being hidden behind a checkbox and not existing/visible when js loaded and gave the input a width (of 0) so only the padding part of the input (first 24px from the left of the button) triggered the file upload popup. This change updates the width of the input to the width of the button when the checkbox is ticked 
* Update the additional_file input width to the button width when the checkbox is toggled
> LIKA-567: Update upload input width with js

- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/ckanext-apicatalog.pot
- ckanext/ckanext-apicatalog/ckanext/apicatalog/schemas/organization.json
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/scheming/organization/about.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/translations.py
This change adds "Choose this if " in front of both new org checkboxes in org edit view (data processing & intermediary org). The original label is still used when displaying in the read view.
* Rename is_intermediary choice label to "Choose this if your organization acts as an intermediary for other organizations."
* Move the previous to choice label text to display_label(?) for display purposes ("display_label": "Organization acts as an intermediary for other organizations.")
* Rename data_processing_outside_eu choice label to "Choose this if your organization processes data outside the EU/EAA countries."
* Move the previous to choice label text to display_label(?) for display purposes ("display_label": "Organization processes data outside the EU/EAA countries.")
* Reordered the two …
> LIKA-561: Rename org checkbox labels

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/scheming/organization/about.html
If organization had descriptions in other languages but not in finnish the other translations weren't shown either. This fixes that behavior so that description is shown on selected language if it's set regardless of the finnish description 
* Show en/sv descriptions if given and corresponding lang is selected regardless of the finnish description
> LIKA-571: Fix org description in other languages if FI is missing

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/scheming/organization/about.html
- ckanext/ckanext-apicatalog/less/layout.less
Placement of the organization's logo on organization/about page got broken most likely when moving the navigation from top to side. This change fixes the logo into a more sensible place on the page.
* Fix placement of the organization logo on organization/about page
Before:
After:
> LIKA-570: Fix organization logo placement

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/organization/read_base.html
- ckanext/ckanext-validate_links/.tx/config
- ckanext/ckanext-validate_links/ckanext/validate_links/model/__init__.py
- ckanext/ckanext-validate_links/ckanext/validate_links/plugin.py
- ckanext/ckanext-validate_links/ckanext/validate_links/views.py
- ckanext/ckanext-validate_links/setup.cfg
- Added tab for viewing organization's broken links
- Added translations
> LIKA-270: Added broken links tab to organization pages for admins

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/organization/index.html
Since the organization index page was changed from listing all organizations by default to filtering to only service providers by default, the change wasn't made very apparent and it might have looked like hundreds of organizations just disappeared. This change adds a mention after the lists organization count that the filter is on and gives you a link shortcut to showing all orgs instead.
> LIKA-573: Add note of filter to org list org count

- ansible/vars/environment-specific/prod.yml
Enable apply_permissions_for_service in prod
* Added apply_permissions_for_service to list of prod plugins
> LIKA-569: Enable apply_permissions_for_service in prod

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/read.html
- ckanext/ckanext-apicatalog/less/components/apply-permissions-for-service.less
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/auth.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/migration/apply_permissions_for_service/versions/244dd92f445e_add_created_timestamp_column.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/migration/apply_permissions_for_service/versions/d7db14126049_clarify_column_names.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/model.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/dashboard.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/manage.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/new.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/notification_email.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/settings.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/snippets/additional_application_info.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/snippets/application_table.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/view.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/package/read_base.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/tests/fixtures.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/tests/test_plugin.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py
- ckanext/ckanext-apply_permissions_for_service/conftest.py
There were quite a bit wrong with apply_permissions_for_service so close to the feature release. A lot of time went to (mostly manual) testing of the feature and unfortunately big chunk of it went to trying to understand the code with all the inconsistencies in naming conventions both in casing (camelCase vs snake_case) and names themselves (subsystem_id instead of target_subsystem_id, subsystem_code instead of subsystem_id, business_code instead of member_code, etc etc.). In addition this change includes a number of fixes ranging from minor tweak to rather significant fix (links didn't open in new tabs & application reception notification email talked about accepting the application when such functionality doesn't exist VS requester subsystem and target subsystem were reversed …
> LIKA-572: Fix several issues with apply_permissions_for_service

- ansible/roles/diagnostics/tasks/api-verifier.yml
- ansible/vars/environment-specific/qa.yml
Api-verifier was not correctly installed to remote
- Add copying the files to ansible
- Use relative paths for spec/validation files in config
> LIKA-542: Fix api-verifier install

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/organization/read_base.html
...provided the user can access it
- Remove condition from organization template
> LIKA-270: Always show broken links menu item in organizations

- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/logic/action.py
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/templates/apply_permissions_for_service/notification_email.html
Service permission application email sending did not work.
- Use target subsystem information when determining email recipient
- Fix email terminology
> LIKA-565: Fix permission application email

- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/ckanext-apicatalog.pot
- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/fi/LC_MESSAGES/ckanext-apicatalog.po
- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/sv/LC_MESSAGES/ckanext-apicatalog.po
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/footer.html
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/tests/test_plugin.py
This PR adds localized but hardcoded link to the footer pointing to [Data Exchange Layer's privacy statement](https://palveluhallinta.suomi.fi/en/sivut/palveluvayla/palvelukuvaus/tietosuoja) as the leftmost hardcoded link (after the CMS page links)
* Add 'Privacy statement' link to the footer
* Update localizations
> LIKA-579: Add privacy statement to the footer

- ansible/roles/ckan/tasks/main.yml
- requirements.in
- requirements.txt
Pip did not parse dependencies with old convention anymore, this updates it to new convention. ckan is installed separately as one cannot install it as editable anymore with requirements.
> Update dependency generation to support newer pip

- ckanext/ckanext-apicatalog/ckanext/apicatalog/fanstatic/javascript/datepicker.js
X-Road services date picker did not work because of a apicatalog_ui merge issue.
- Added autosubmit implementation to datepicker component
> LIKA-591: Reimplement datepicker autosubmit

- ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/utils.py
Front page featured subsystems should contain only subsystems with a description and at least one service
- Added `sort` parameter to `package_generator`, defaults to default sorting
- Modified `get_homepage_datasets` to filter the results based on criteria
- The implementation fetches candidates in a paged fashion to reduce the likely amount of data fetched each front page load
> LIKA-593: Only show subsystems with a description and services on front page

- ansible/roles/ckan/files/patches/fix_detection_of_xlsx_mimetype.patch
- ansible/roles/ckan/templates/ckan.ini.j2
- ansible/roles/ckan/vars/main.yml
- ckanext/ckanext-apply_permissions_for_service/ckanext/apply_permissions_for_service/views.py
In CKAN 2.9.8 default files types were limited in uploader due to security reasons, this adds allowed filetypes to permission applications, the list is based on what the UI says are allowed.
Adds exception handling to uploading permission application files.
Adds allowed file types to permission applications.
Fixes detection of XLSX files in ckan core.
> LIKA-604: Fix adding pdfs to permission applications

- .gitmodules
Ckanext-contact was still in the repo. Remove the submodule.
- Remove submodule
> Remove ckanext-contact submodule

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/dataviewer/openapi_view.html
OpenAPI viewer had unnecessary and confusing default features enabled.
- Disable "Try it out" functionality as it doesn't work without a server address
- Remove snippets for the same reason
- Add a description to generated OpenAPI files to fix infinite spinner issue
- Harmonize fonts used with rest of the site
> LIKA-600: OpenAPI viewer style improvements

- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/dataviewer/openapi_view.html
Duplicate OpenAPI description URL in Swagger preview
- Hide the link using CSS as there is no configuration for it
> LIKA-600: Hide redundant OpenAPI description URL in preview

- ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/tests/test_plugin.py
Subsystems removed form X-Road were visible with a direct link
- Raise ObjectNotFound for removed subsystems if the user is not a sysadmin
- Fix subsystem search result count
> LIKA-606: Fix subsystem search result count, hide removed subsystems

- ansible/roles/ckan/tasks/main.yml
Cronjob sent unnecessary notifications due to `--force`
- Remove --force from cron job parameters
> LIKA-605: Don't send unnecessary harvester status notifications

- ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/tests/test_plugin.py
Use permission labels to hide subsystems removed from x-road instead of search result filtering
- Remove all permission labels from xroad_removed subsystems
- Fix tests
> LIKA-606: use permission labels to hide removed subsystems

- ansible/vars/environment-specific/qa.yml
- ansible/vars/environment-specific/test.yml
- ansible/vars/environment-specific/vagrant.yml
Differentiate between deploy environments based on site_title
- Set a distinct site_title for each environment
> LIKA-605: Modify site_titles to differentiate between environments

- ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/schemas/organization.json
- ckanext/ckanext-apicatalog/ckanext/apicatalog/validators.py
Some organizations have an empty string or null value in old_business_ids property, which causes a validation error when the organization is updated. Added a validator to interpret those as empty lists for compatibility.
> LIKA-612: Interpret empty old_business_ids as an empty list

- ansible/vars/environment-specific/qa.yml
- ansible/vars/environment-specific/test.yml
Changes in xroad security servers reserved 443 to other uses, integrations work from 8443 instead.
> Due to changes in xroad, security server in FI-TEST responds in 8443 instead

- ansible/roles/ckan/files/patches/remove_free_fontawesome.patch
fontawesome generated error in logs.
openapi viewer used old pylons controller routes which do not exist anymore.
> Additional fixes for ckan upgrade

- ansible/roles/ckan/files/patches/fix_missing_robotstxt.patch
- ansible/roles/ckan/tasks/main.yml
- ansible/roles/ckan/templates/robots.txt.j2
- ansible/roles/ckan/vars/main.yml
- ckanext/ckanext-apicatalog/.gitignore
CKAN has an issue with robots.txt when using bootstrap 3 templates, this creates the missing template via patch and modifies it in an extension depending on ansible configuration.
> Fix server error with robots.txt

- ckanext/ckanext-apicatalog/ckanext/apicatalog/auth.py
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/organization/edit_base.html
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/organization/read_base.html
Group dict has been removed from globals as it was deprecated feature, fixes by adding id to auth call explicitely.
> Fix read_members auth function

- ckanext/ckanext-apicatalog/ckanext/apicatalog/plugin.py
Should be using `unicode_safe` instead of `six.text_type` which is unicode, ckan gives an error with validators that aren't user defined.
> Fix server error in ckan admin config

- ansible/roles/ckan/tasks/main.yml
- requirements.in
- requirements.txt
Upgrades ckan to 2.10.6 and compiles requirements.
> Upgrade ckan to 2.10.6

- requirements.txt
Pysolr upgraded to fix indexing error while deleting subsystems with xml characters on ids. Next ckan won't require manual update.
> Upgrade pysolr to fix indexing error with xml characters on ids

- ckanext/ckanext-apicatalog/ckanext/apicatalog/i18n/ckanext-apicatalog.pot
- ckanext/ckanext-apicatalog/ckanext/apicatalog/templates/package/search.html
- Change suomi.fi instruction link url in dataset search
> LIKA-644: Update suomi.fi instruction link URL

- ckanext/ckanext-validate_links/ckanext/validate_links/migration/validate_links/versions/6cf6e534f8f6_add_link_validation_tables.py
Switching to alembic broke deploy due to pre-existing db tables. 
Added `if_not_exists=True` to migration so it doesn't try to overwrite tables
> LIKA-636: Fix validate_links alembic migration breaking on pre-existing tables

- ckanext/ckanext-validate_links/ckanext/validate_links/migration/validate_links/versions/6cf6e534f8f6_add_link_validation_tables.py
if_not_exists was introduced in alembic 1.13.3. CKAN requires 1.13.2. Create a workaround.
manually check the list of tables before creating.
> LIKA-636: fix alembic create_table if_not_exists not being present in used version

- ckanext/ckanext-apicatalog/ckanext/apicatalog/validators.py
Python code shouldn't use template helpers.
> Fix error in harvesting, helper check_access assumes user exist, toolkit check_access requires context

- ckanext/ckanext-apicatalog/ckanext/apicatalog/schemas/organization.json
- ckanext/ckanext-apicatalog/ckanext/apicatalog/tests/test_plugin.py
Previous implementation interpreted none and more than two old business id entries as a list, but exactly one was interpreted as a string, causing an error.
- Switch from `list_to_json_string` to `scheming_multiple_text` which actually does the correct thing after the empty case is handled by `empty_to_list`
> LIKA-687: Fix entering exactly one old business ID not being interpreted as a list

- .github/workflows/main.yml
Adds codecov coverage uploads to unit tests of the repository.
Removes running test workflow on push, as pull requests would run them twice. The workflow can still be run on UI if needed for branch.
> Add codecov to test workflow
